# Generated by Django 5.1.5 on 2025-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0002_customuser_facebook_customuser_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
