# Generated by Django 5.1.5 on 2025-02-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="job_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
