# Generated by Django 5.1.5 on 2025-02-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0004_customuser_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
