# Generated by Django 5.1.5 on 2025-02-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
